Add some shields to README.md
IBM-Quantum-Prototypes/quantum-kernel-training pull request #19
Opened 2022-02-22 02:28 UTC by garrison

Preview at: https://github.com/IBM-Quantum-Prototypes/quantum-kernel-training/tree/shields#readme

The precise list of shields will surely evolve, but this seems like a reasonable starting point.

2022-02-23 17:27 UTC, calebj15 requested changes
Ad OS shield {Linux(test for ubuntu and ubi), macOS, Windows}

2022-02-23 17:27 UTC, calebj15 commented on README.md
> +[![License](https://img.shields.io/github/license/IBM-Quantum-Prototypes/quantum-kernel-training?color=informational&label=License)](https://github.com/IBM-Quantum-Prototypes/quantum-kernel-training/
Do we want to back-support Qiskit (1 version? 2?)

2022-02-23 17:27 UTC, calebj15 commented on README.md
> +[![License](https://img.shields.io/github/license/IBM-Quantum-Prototypes/quantum-kernel-training?color=informational&label=License)](https://github.com/IBM-Quantum-Prototypes/quantum-kernel-training/
No

2022-02-23 20:25 UTC, garrison commented
How does the current preview look?

2022-02-23 20:28 UTC, garrison commented
BTW, I didn't enable a coverage badge because there is not a coverage workflow in this repository -- everything is a notebook test.

2022-02-28 21:44 UTC, calebj15 approved these changes

2022-02-28 21:44 UTC, merged